version: '3.8'

services:
  avito_test:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - pgdbdate:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"
volumes:
  pgdbdate:
